name: Update News Sitemap and Indexing

on:
  schedule:
    # S'exécute toutes les 2 heures (format Cron)
    - cron: '0 */2 * * *'
  workflow_dispatch: # Permet de le lancer manuellement pour tester

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Configuration de Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Installation des dépendances
        run: |
          pip install feedparser google-api-python-client google-auth

      - name: Execution du Workflow SEO
        env:
          # Ici on fait le lien avec ta clé API secrète
          GSC_JSON_KEY: ${{ secrets.GSC_JSON_KEY }}
        run: python main.py

      - name: Commit et Push du sitemap généré
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs/newssitemap.xml
          git commit -m "Auto-update sitemap [skip ci]" || exit 0
          git push
