name: Update News Sitemap

on:
  schedule:
    - cron: '0 0 * * *' # Mise à jour auto chaque nuit à minuit
  workflow_dispatch:      # Permet de cliquer sur un bouton pour forcer la mise à jour

jobs:
  update-rss:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install feedparser
        run: pip install feedparser

      - name: Update sitemap file
        run: python update_sitemap.py

      - name: Commit and Push
        run: |
          git config --global user.name "Sitemap Bot"
          git config --global user.email "actions@github.com"
          git add docs/newssitemap.xml
          git commit -m "auto: update newssitemap.xml from RSS" || echo "Aucun changement détecté"
          git push
