name: Update Google News Sitemap

on:
  schedule:
    - cron: '*/5 * * * *' # S'exécute environ toutes les 5 minutes
  workflow_dispatch:      # Permet de le lancer manuellement pour test

jobs:
  update-sitemap:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Indispensable pour que le robot puisse publier le fichier

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install feedparser

      - name: Run update script
        run: python update_sitemap.py

      - name: Commit and Push changes
        run: |
          git config --global user.name "GoogleNews-Bot"
          git config --global user.email "actions@github.com"
          git add docs/newssitemap.xml
          # Le script ne fera un commit que s'il y a de nouveaux articles
          git commit -m "auto: mise à jour sitemap Google News" || echo "Aucun nouvel article détecté"
          git push
